### ISSUE TITLE
GUI crashes in them choice

### ISSUE THREAD

**Issue by PaulDGx** [PhoenixPE/PhoenixPE#4]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

Under Tweaks / Theme
Changing from one theme to another either (50/50) crashes PEBakery to the desktop or reports the following error.

[Error] [E] WriteInterface - The process cannot access the file 'G:\PEBakery\PhoenixPE-2022-05-22\Projects\PhoenixPE\Tweaks\Theme.script' because it is being used by another process. (Else,WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,False) (Line 693)

PEBakery V 1.0.0
PhoenixPE V 1.0.2.0

PaulDG

**Comment by homes32** [comment]
Thanks for the report. I am able to reproduce this on my system as well.

It looks like the issue may be caused by a race condition in PEBakery.

It does not matter which `WriteInterface` command is run or not.
```
[ToggleCustomTheme]

// Annihilator
If,%cmb_Theme%,Equal,"Annihilator",WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,True
Else,WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,False

// Custom
//If,%cmb_Theme%,Equal,"Custom",Set,%Toggle%,True
//Else,Set,%Toggle%,False
//WriteInterface,Visible,%ScriptFile%,Interface,lbl_SelectCustomTheme,%Toggle%
//WriteInterface,Visible,%ScriptFile%,Interface,fb_CustomTheme,%Toggle%
```
vs

```
[ToggleCustomTheme]

// Annihilator
//If,%cmb_Theme%,Equal,"Annihilator",WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,True
//Else,WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,False

// Custom
If,%cmb_Theme%,Equal,"Custom",Set,%Toggle%,True
Else,Set,%Toggle%,False
WriteInterface,Visible,%ScriptFile%,Interface,lbl_SelectCustomTheme,%Toggle%
WriteInterface,Visible,%ScriptFile%,Interface,fb_CustomTheme,%Toggle%
```
both result in crash.

swapping `WriteInterface,Visible` for the depreciated `Visible` command also causes the same crash, so the issue may not be exclusive, or even directly related to the `WriteInterface` command.

Introducing delay with `Wait` side-steps the issue and appears to give whatever process is blocking time to finish.
```
[ToggleCustomTheme]
Wait,1
// Annihilator
If,%cmb_Theme%,Equal,"Annihilator",WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,True
Else,WriteInterface,Visible,%ScriptFile%,Interface,lbl_DisableWallpaperScript,False

// Custom
If,%cmb_Theme%,Equal,"Custom",Set,%Toggle%,True
Else,Set,%Toggle%,False
Wait,1
WriteInterface,Visible,%ScriptFile%,Interface,lbl_SelectCustomTheme,%Toggle%
Wait,1
WriteInterface,Visible,%ScriptFile%,Interface,fb_CustomTheme,%Toggle%

```

Reducing the .script file size, by deleting the Annihilator.7z theme attachment also prevents the issue.

**Comment by homes32** [comment]
Crash dump

```
PEBakery cannot continue due to an internal error.
Please post the crash log to the PEBakery issue tracker.

[PEBakery]
Version   | 1.0.1 (Build 20220605)
CrashTime | 2022.06.05 14:53:32 -05:00

[Host]
Windows       | 10.0.19044.0 (x64)
.NET Runtime  | 6.0.5 (x64)
Language      | English (United States)
ANSI Encoding | Western European (Windows) (1252)
OEM Encoding  | Western European (Windows) (1252)

[Exception Trace]
System.IO.IOException: The process cannot access the file 'C:\CODE\pebakery\PEBakery\bin\Debug\net6.0-windows7.0\Projects\PhoenixPE\Tweaks\Theme.script' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at PEBakery.Helper.FileHelper.FileReplaceEx(String srcPath, String destPath) in C:\CODE\pebakery\PEBakery.Helper\FileHelper.cs:line 292
   at PEBakery.Ini.IniReadWriter.InternalWriteKeys(String filePath, List`1 inputKeys) in C:\CODE\pebakery\PEBakery.Ini\IniReadWriter.cs:line 514
   at PEBakery.Core.UIControl.Update() in C:\CODE\pebakery\PEBakery.Core\UIControl.cs:line 256
   at PEBakery.Core.UIRenderer.ComboBox_LostFocus(Object sender, RoutedEventArgs e) in C:\CODE\pebakery\PEBakery.Core\UIRenderer.cs:line 615
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.OnLostFocus(RoutedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Controls.ComboBox.OnIsDropDownOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.ComboBox.Close()
   at System.Windows.Controls.ComboBox.NotifyComboBoxItemMouseUp(ComboBoxItem comboBoxItem)
   at System.Windows.Controls.ComboBoxItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PEBakery.App.Main()
 



```

**Comment by ied206** [comment]
Also reproduced in my system. 
It seems the race condition was caused by two threads both trying to save to a single file.
I will add a ReadWriteLock to `IniReadWriter` to prevent such race conditions.
